### ISSUE TITLE
Exposed Username and password in URI

### ISSUE THREAD

**Issue by RiRa12621** [aleena9995/Devops#1]
Potential security breach. See /TERRAFORM/EC2-DEV/provision/playbook.yml

**Comment by aleena9995** [comment]
removed

**Comment by RiRa12621** [comment]
you also have your AWS credentials on here 
https://github.com/aleena9995/Devops/blob/master/TERRAFORM/rabbitmq-cluster-terraform-ansible/main.tf
really don't put any secrets somewhere public

**Comment by aleena9995** [comment]
Removed
